name: publish-nuget
on:
  push:
    tags: ["v*"]
permissions:
  contents: read
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github "https://nuget.pkg.github.com/yuribsl/index.json"
      - name: Pack
        run: dotnet pack -c Release
      - name: Publish
        run: dotnet nuget push "**/*.nupkg" --source github --skip-duplicate